name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: codeowners-generator
      - name: Checkout repository
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - name: Build package
        run: |
          npm run build
          npm run build-cli
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
